"""Load the public Udacity S3 datasets into the local Compose PostgreSQL."""

import json
import os
import re
from urllib.parse import urlparse

import boto3
import psycopg2
from botocore import UNSIGNED
from botocore.config import Config
from psycopg2.extras import execute_values

from sql_queries import (
    artist_table_insert,
    create_table_queries,
    drop_table_queries,
    song_table_insert,
    songplay_table_insert,
    time_table_insert,
    user_table_insert,
)


EVENT_COLUMNS = (
    "artist", "auth", "firstName", "gender", "itemInSession", "lastName",
    "length", "level", "location", "method", "page", "registration",
    "sessionId", "song", "status", "ts", "userAgent", "userId",
)
SONG_COLUMNS = (
    "num_songs", "artist_id", "artist_latitude", "artist_longitude",
    "artist_location", "artist_name", "song_id", "title", "duration", "year",
)
NUMERIC_COLUMNS = {
    "itemInSession", "length", "registration", "sessionId", "status", "ts",
    "userId", "num_songs", "artist_latitude", "artist_longitude", "duration", "year",
}


def postgres_ddl(redshift_ddl):
    """Translate the small set of Redshift-only table options used by this project."""
    ddl = re.sub(r"\n(?:DISTKEY|SORTKEY)\([^\n]*\)|\nDISTSTYLE ALL", "", redshift_ddl)
    return ddl.replace(
        "BIGINT IDENTITY(0,1)", "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    )


def s3_bucket_prefix(s3_url):
    parsed = urlparse(s3_url)
    if parsed.scheme != "s3" or not parsed.netloc:
        raise ValueError(f"Expected an s3:// URL, got {s3_url!r}")
    return parsed.netloc, parsed.path.lstrip("/").rstrip("/")


def iter_s3_json(s3, s3_url):
    bucket, prefix = s3_bucket_prefix(s3_url)
    paginator = s3.get_paginator("list_objects_v2")
    for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
        for item in page.get("Contents", []):
            key = item["Key"]
            if not key.endswith(".json"):
                continue
            body = s3.get_object(Bucket=bucket, Key=key)["Body"]
            try:
                yield from iter_json_values(
                    body.read(), f"s3://{bucket}/{key}"
                )
            finally:
                body.close()


def iter_json_values(raw, source):
    """Yield every JSON value in an object, including newline-delimited records."""
    text = raw.decode("utf-8-sig")
    decoder = json.JSONDecoder()
    position = 0
    while position < len(text):
        while position < len(text) and text[position].isspace():
            position += 1
        if position == len(text):
            break
        try:
            value, position = decoder.raw_decode(text, position)
        except json.JSONDecodeError as exc:
            line = text.count("\n", 0, exc.pos) + 1
            raise ValueError(f"Invalid JSON in {source} at line {line}: {exc}") from exc
        if isinstance(value, list):
            yield from value
        else:
            yield value


def recreate_tables(cur, conn):
    for query in drop_table_queries:
        cur.execute(query)
    for query in create_table_queries:
        cur.execute(postgres_ddl(query))
    conn.commit()


def load_json_rows(cur, conn, s3, s3_url, table, columns):
    # PostgreSQL folds unquoted camelCase DDL names to lowercase, as it does in
    # the shared INSERT statements, so keep these identifiers unquoted here too.
    column_names = ", ".join(columns)
    insert_sql = f"INSERT INTO {table} ({column_names}) VALUES %s"
    batch = []
    count = 0
    for record in iter_s3_json(s3, s3_url):
        batch.append(
            tuple(
                None
                if column in NUMERIC_COLUMNS
                and isinstance(record.get(column), str)
                and not record[column].strip()
                else record.get(column)
                for column in columns
            )
        )
        if len(batch) >= 1000:
            execute_values(cur, insert_sql, batch)
            conn.commit()
            count += len(batch)
            batch.clear()
    if batch:
        execute_values(cur, insert_sql, batch)
        conn.commit()
        count += len(batch)
    print(f"Loaded {count:,} rows into {table}", flush=True)


def main():
    s3 = boto3.client(
        "s3",
        region_name=os.getenv("AWS_DEFAULT_REGION", "us-west-2"),
        config=Config(signature_version=UNSIGNED),
    )
    conn = psycopg2.connect(
        host=os.getenv("WAREHOUSE_HOST", "localhost"),
        port=os.getenv("WAREHOUSE_PORT", "5432"),
        dbname=os.getenv("WAREHOUSE_DB", "sparkify"),
        user=os.getenv("WAREHOUSE_USER", "sparkify"),
        password=os.getenv("WAREHOUSE_PASSWORD", "sparkify"),
    )
    try:
        with conn.cursor() as cur:
            recreate_tables(cur, conn)
            load_json_rows(
                cur, conn, s3, os.getenv("LOG_DATA", "s3://udacity-dend/log_data"),
                "staging_events", EVENT_COLUMNS,
            )
            load_json_rows(
                cur, conn, s3, os.getenv("SONG_DATA", "s3://udacity-dend/song_data"),
                "staging_songs", SONG_COLUMNS,
            )
            for query in (
                songplay_table_insert,
                user_table_insert,
                song_table_insert,
                artist_table_insert,
                time_table_insert,
            ):
                if query == songplay_table_insert:
                    query = query.replace(
                        "TIMESTAMP 'epoch' + e.ts / 1000.0 * INTERVAL '1 second'",
                        "TO_TIMESTAMP(e.ts / 1000.0)",
                    )
                cur.execute(query)
                conn.commit()
        print("Local warehouse ETL complete", flush=True)
    finally:
        conn.close()


if __name__ == "__main__":
    main()
